const RUBRICS={
1:[["Version Control",10],["Documentation Site",10],["Getting Started / Dev Guides",5],["Work Tracker",5],["Git Methodology",5],["Project Methodology",10],["Tech Stack",5],["Stakeholder Interaction",10],["Initial Design & Dev Plan",20],["Implementation",20]],
2:[["Core Features",25],["Automated Testing",10],["Stakeholder Reviews",10],["API",15],["User Feedback",10],["Project Methodology",10],["Bug Tracker",5],["Database Documentation",5],["Third-Party Code Documentation",5],["Testing Documentation",5]],
3:[["User Feedback",10],["Automated Testing",10],["Feature Implementation",20],["API Implementation",20],["Performance",5],["Improvement",5],["Documentation",15],["Project Methodology",15]],
4:[["Database: Data",3],["Database: Deployment",2],["Database: Structure",5],["API: Availability",3],["API: Architecture",5],["API: Deployment",2],["API: Performance",5],["API: Design",10],["App: Accessibility",5],["App: Aesthetics",3],["App: User Experience",5],["App: Deployment",2],["App: Performance",5],["App: Features",10],["App: Responsiveness",5],["App: Structure",5],["Misc: Git Methodology",5],["Misc: Integration",7],["Misc: Testing",8],["Misc: Tools",5]]};
const SPRINTS={1:{title:"Project setup",due:"25 Aug 2026",goal:"Repositories, blockers, methodology, design and supporting foundations."},2:{title:"Strong base",due:"15 Sep 2026",goal:"Core features, testing, reviews, API, feedback and technical documentation."},3:{title:"Near complete",due:"29 Sep 2026",goal:"Most features working, qualitative reviews, performance and refined documentation."},4:{title:"Project submission",due:"11 Oct 2026",goal:"Stable database, API, app, integration, testing and delivery practice."}};
const STARTUP=[
 ["role-selection.jpg","Roles were allocated democratically","The poll records one person selecting each of Members 1–6, supporting ownership and accountability.","Project methodology · Work tracker"],
 ["sprint-planning.jpg","The sprint plan was circulated","Members were asked to read Sprint 1, review dependencies and select roles before meeting.","Project methodology · Initial plan"],
 ["git-methodology.jpg","A branch and integration method was agreed","The group agreed that members work on branches and one integration owner merges completed work.","Version control · Git methodology"],
 ["database-decision.jpg","The database/API direction was discussed","The group compared Supabase with PostgreSQL and Express before implementation settled on Express, Prisma and Neon.","Tech stack · Interaction"],
 ["neon-access.jpg","Shared database access was coordinated","Invitations and access instructions were shared; replies also record a genuine onboarding blocker.","Getting Started · Interaction"],
 ["member6-handoff.jpg","Member 6 published a technical handoff","The branch, stack, schema, demo data and workflow rules were communicated to the team.","Implementation · Dev guides"],
 ["ci-blocker.jpg","The CI blocker was communicated honestly","The team recorded that remote CI was blocked by the lecturer-managed runner while local testing remained possible.","Methodology · Risk management"]];
let data={meetings:[],planning:[],documents:[],rubric:{}},sprint=1;
const $=s=>document.querySelector(s); const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function boot(){const base=await fetch("data/site-data.json").then(r=>r.json()).catch(()=>data);const local=localStorage.getItem("tutorMxDraft");data=local?JSON.parse(local):base;renderAll()}
function save(){localStorage.setItem("tutorMxDraft",JSON.stringify(data));renderAll()}
function renderAll(){renderStartup();renderMeetings();renderPlanning();renderDocuments();renderRubric()}
function renderStartup(){$("#startup-grid").innerHTML=STARTUP.map((x,i)=>`<figure><a href="evidence/${x[0]}" target="_blank"><img src="evidence/${x[0]}" alt="Team communication evidence ${i+1}"></a><figcaption><small>Evidence ${i+1}</small><h3>${x[1]}</h3><p>${x[2]}</p><b>${x[3]}</b></figcaption></figure>`).join("")}
function image(src,alt){return src?`<a class="proof" href="${src}" target="_blank"><img src="${src}" alt="${esc(alt)} proof"></a>`:""}
function renderMeetings(){const e=$("#meeting-list");e.innerHTML=data.meetings.length?data.meetings.map(x=>`<article>${image(x.proof,x.title)}<div><small>${esc(x.type)} · ${esc(x.date)}</small><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><h4>Decisions & actions</h4><p>${esc(x.outcomes)}</p><span>${esc(x.attendees)}</span><button class="text danger" onclick="removeItem('meetings','${x.id}')">Delete draft</button></div></article>`).join(""):`<div class="empty">No meeting records yet. Add each sprint ceremony or stakeholder meeting with decisions, actions and proof.</div>`}
function renderPlanning(){const e=$("#planning-list");e.innerHTML=data.planning.length?data.planning.map(x=>`<article>${image(x.proof,x.title)}<div><small>Sprint ${x.sprint} · ${esc(x.category)} · ${esc(x.date)}</small><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><h4>Outcome / next action</h4><p>${esc(x.outcomes)}</p><button class="text danger" onclick="removeItem('planning','${x.id}')">Delete draft</button></div></article>`).join(""):`<div class="empty">No additional planning records yet. Existing startup decisions are preserved above.</div>`}
function renderDocuments(){$("#document-list").innerHTML=data.documents.map(x=>`<a href="${esc(x.url)}" target="_blank"><span>PDF</span><div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p></div><b>Open ↗</b></a>`).join("")}
function renderRubric(){const tabs=$("#sprint-tabs");tabs.innerHTML=Object.keys(SPRINTS).map(n=>`<button class="${+n===sprint?'active':''}" onclick="sprint=${n};renderRubric()">Sprint ${n}</button>`).join("");const items=RUBRICS[sprint];let done=0;items.forEach(([name,w])=>{if(data.rubric[`${sprint}:${name}`]?.status==="Complete")done+=w});$("#rubric-summary").innerHTML=`<div><b>Sprint ${sprint}: ${SPRINTS[sprint].title}</b><span>Due ${SPRINTS[sprint].due}</span><p>${SPRINTS[sprint].goal}</p></div><strong>${done}% marked complete</strong>`;$("#rubric-list").innerHTML=items.map(([name,w])=>{const key=`${sprint}:${name}`,v=data.rubric[key]||{status:sprint===1&&["Documentation Site","Getting Started / Dev Guides","Tech Stack"].includes(name)?"In progress":"Future plan",evidence:""};return `<article><div><span>${w}%</span><h3>${name}</h3></div><select aria-label="${name} status" onchange="updateRubric('${esc(key)}','status',this.value)">${["Future plan","In progress","Blocked","Complete"].map(o=>`<option ${v.status===o?'selected':''}>${o}</option>`).join("")}</select><textarea aria-label="${name} evidence" placeholder="Evidence link, summary or next action" onchange="updateRubric('${esc(key)}','evidence',this.value)">${esc(v.evidence)}</textarea></article>`}).join("")}
window.updateRubric=(key,field,value)=>{data.rubric[key]={...(data.rubric[key]||{}),[field]:value};save()};window.removeItem=(type,id)=>{if(confirm("Delete this local draft record?")){data[type]=data[type].filter(x=>x.id!==id);save()}};
function fileData(file,max=1500000){return new Promise((resolve,reject)=>{if(!file)return resolve("");if(file.size>max)return reject(new Error("Image is larger than 1.5 MB. Compress it first."));const r=new FileReader;r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>$("#"+b.dataset.open).showModal());
$("#meeting-form").addEventListener("submit",async e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const f=new FormData(e.target);try{data.meetings.unshift({id:crypto.randomUUID(),title:f.get("title"),date:f.get("date"),type:f.get("type"),attendees:f.get("attendees"),summary:f.get("summary"),outcomes:f.get("outcomes"),proof:await fileData(f.get("proof"))});save();e.target.reset();$("#meeting-dialog").close()}catch(err){alert(err.message)}});
$("#planning-form").addEventListener("submit",async e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const f=new FormData(e.target);try{data.planning.unshift({id:crypto.randomUUID(),title:f.get("title"),date:f.get("date"),sprint:+f.get("sprint"),category:f.get("category"),summary:f.get("summary"),outcomes:f.get("outcomes"),proof:await fileData(f.get("proof"))});save();e.target.reset();$("#planning-dialog").close()}catch(err){alert(err.message)}});
$("#document-form").addEventListener("submit",e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const f=new FormData(e.target);data.documents.push({id:crypto.randomUUID(),title:f.get("title"),summary:f.get("summary"),url:f.get("url")});save();e.target.reset();$("#document-dialog").close()});
$("#export-btn").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="site-data.json";a.click();URL.revokeObjectURL(a.href)};$("#import-btn").onclick=()=>$("#import-file").click();$("#import-file").onchange=async e=>{try{data=JSON.parse(await e.target.files[0].text());save()}catch{alert("That file is not valid Tutor Mx site data.")}};$("#reset-btn").onclick=()=>{if(confirm("Discard every unpublished edit on this device?")){localStorage.removeItem("tutorMxDraft");location.reload()}};$("#menu").onclick=()=>$("#nav").classList.toggle("open");boot();
